# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d06e16a13b70725aa6f0b454f1debd1e2942a5a66c0cbc154e4cb08b14e430ba10a51e9cf1d2ba1bc1d49bb4ee8bbbf61344d43c750def19fb43ac3569ed602f

test:
  secret_key_base: 8bac9d892146b151823744f56ef201c47dc43aa37701344b97d1e8451764025c22f6bd5e20332688e1a2ac3f9a6edc70f68749b5e8c2372d93ed6b99dac8f5d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
